/**
 * Share Service
 * Handles result sharing via clipboard, email, SMS, and PDF export
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

// @ts-ignore - Clipboard might not have types
import Clipboard from '@react-native-clipboard/clipboard';

export interface ShareData {
  calculatorType: string;
  calculatorTitle: string;
  inputs: Record<string, string | number | boolean | undefined>;
  result: {
    value: string;
    label: string;
    details?: Record<string, string | number>;
  };
  formula?: string;
  necArticle: string;
  necReference: string;
  warnings?: string[];
  timestamp?: Date;
}

/**
 * Generate formatted text for clipboard/SMS sharing
 */
export function generateShareText(data: ShareData): string {
  const date = data.timestamp ? formatDate(data.timestamp) : formatDate(new Date());
  
  let text = `Conduit & Wire Pro - ${data.calculatorTitle}\n`;
  text += `Generated: ${date}\n`;
  text += '─'.repeat(30) + '\n\n';
  
  // Inputs
  text += 'INPUTS:\n';
  Object.entries(data.inputs).forEach(([key, value]) => {
    if (value !== undefined && value !== '') {
      text += `• ${formatLabel(key)}: ${value}\n`;
    }
  });
  
  text += '\n';
  
  // Result
  text += 'RESULT:\n';
  text += `${data.result.label}: ${data.result.value}\n`;
  
  if (data.result.details) {
    Object.entries(data.result.details).forEach(([key, value]) => {
      text += `• ${formatLabel(key)}: ${value}\n`;
    });
  }
  
  // Formula
  if (data.formula) {
    text += `\nFORMULA:\n${data.formula}\n`;
  }
  
  // NEC Reference
  text += `\nNEC Reference: ${data.necReference}\n`;
  
  // Warnings
  if (data.warnings && data.warnings.length > 0) {
    text += '\n⚠️ WARNINGS:\n';
    data.warnings.forEach(warning => {
      text += `• ${warning}\n`;
    });
  }
  
  text += '\n─'.repeat(30) + '\n';
  text += 'Generated by Conduit & Wire Pro\n';
  text += 'For reference only. Verify with NEC 2023.';
  
  return text;
}

/**
 * Copy formatted text to clipboard
 */
export async function copyToClipboard(data: ShareData): Promise<void> {
  const text = generateShareText(data);
  Clipboard.setString(text);
}

/**
 * Generate mailto: URL for email sharing
 */
export function generateEmailUrl(data: ShareData): string {
  const subject = encodeURIComponent(`CWP Calculation: ${data.calculatorTitle}`);
  const body = encodeURIComponent(generateShareText(data));
  return `mailto:?subject=${subject}&body=${body}`;
}

/**
 * Open email client with pre-filled content
 */
export function shareToEmail(data: ShareData): void {
  const { Linking } = require('react-native');
  Linking.openURL(generateEmailUrl(data));
}

/**
 * Generate SMS text (shorter format for SMS limits)
 */
export function generateSMSText(data: ShareData): string {
  const date = data.timestamp ? formatDateShort(data.timestamp) : formatDateShort(new Date());
  
  let text = `${data.calculatorTitle} (${date})\n`;
  text += `Result: ${data.result.value}\n`;
  
  if (data.formula) {
    text += `Formula: ${data.formula}\n`;
  }
  
  text += `NEC ${data.necReference}`;
  
  return text;
}

/**
 * Open SMS app with pre-filled message
 */
export function shareToSMS(data: ShareData): void {
  const { Linking } = require('react-native');
  const text = encodeURIComponent(generateSMSText(data));
  const url = Platform.OS === 'ios' ? `sms:&body=${text}` : `sms:?body=${text}`;
  Linking.openURL(url);
}

/**
 * Generate PDF report
 */
export async function generatePDF(data: ShareData): Promise<string> {
  const html = generatePDFHTML(data);
  
  const { uri } = await Print.printToFileAsync({
    html,
    base64: false,
  });
  
  return uri;
}

/**
 * Share PDF via native share sheet
 */
export async function sharePDF(data: ShareData): Promise<void> {
  const pdfUri = await generatePDF(data);
  
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(pdfUri, {
      mimeType: 'application/pdf',
      dialogTitle: `Share ${data.calculatorTitle} Results`,
    });
  } else {
    throw new Error('Sharing is not available on this device');
  }
}

/**
 * Generate professional PDF HTML template
 */
function generatePDFHTML(data: ShareData): string {
  const date = data.timestamp ? formatDate(data.timestamp) : formatDate(new Date());
  const time = data.timestamp ? formatTime(data.timestamp) : formatTime(new Date());
  
  // Build inputs table rows
  const inputsRows = Object.entries(data.inputs)
    .filter(([_, value]) => value !== undefined && value !== '')
    .map(([key, value]) => `
      <tr>
        <td class="input-label">${formatLabel(key)}</td>
        <td class="input-value">${formatValue(value)}</td>
      </tr>
    `).join('');
  
  // Build result details rows
  const detailsRows = data.result.details ? 
    Object.entries(data.result.details).map(([key, value]) => `
      <tr>
        <td class="detail-label">${formatLabel(key)}</td>
        <td class="detail-value">${value}</td>
      </tr>
    `).join('') : '';
  
  // Build warnings HTML
  const warningsHTML = data.warnings && data.warnings.length > 0 ? `
    <div class="warnings">
      <div class="warnings-title">⚠️ WARNINGS</div>
      ${data.warnings.map(w => `<div class="warning-item">${w}</div>`).join('')}
    </div>
  ` : '';
  
  // Build formula section
  const formulaHTML = data.formula ? `
    <div class="formula-section">
      <div class="section-title">FORMULA</div>
      <div class="formula-box">
        <code>${data.formula}</code>
      </div>
    </div>
  ` : '';
  
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>CWP Calculation Report</title>
  <style>
    @page { margin: 0.5in; }
    * { box-sizing: border-box; }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      margin: 0;
      padding: 0;
      color: #1a1a1a;
      line-height: 1.5;
    }
    
    .header {
      background: linear-gradient(135deg, #1E2337 0%, #141829 100%);
      color: white;
      padding: 30px;
      text-align: center;
      border-radius: 8px;
      margin-bottom: 24px;
    }
    
    .logo {
      font-size: 14px;
      font-weight: 700;
      letter-spacing: 2px;
      color: #4A9EFF;
      margin-bottom: 8px;
    }
    
    .app-name {
      font-size: 24px;
      font-weight: 800;
      margin-bottom: 4px;
    }
    
    .report-type {
      font-size: 16px;
      color: #8E8E93;
      font-weight: 600;
    }
    
    .content { padding: 0 8px; }
    
    .calc-title {
      font-size: 20px;
      font-weight: 700;
      color: #1a1a1a;
      margin-bottom: 4px;
      border-bottom: 2px solid #4A9EFF;
      padding-bottom: 8px;
    }
    
    .date-line {
      font-size: 12px;
      color: #636366;
      margin-bottom: 20px;
    }
    
    .section {
      margin-bottom: 20px;
      page-break-inside: avoid;
    }
    
    .section-title {
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 1px;
      color: #8E8E93;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    
    table.inputs-table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 16px;
    }
    
    table.inputs-table td {
      padding: 10px 12px;
      border-bottom: 1px solid #E5E5EA;
    }
    
    table.inputs-table tr:last-child td { border-bottom: none; }
    
    .input-label {
      font-size: 13px;
      color: #636366;
      width: 40%;
    }
    
    .input-value {
      font-size: 13px;
      font-weight: 600;
      color: #1a1a1a;
    }
    
    .result-box {
      background: linear-gradient(135deg, #F8F9FA 0%, #FFFFFF 100%);
      border: 2px solid #4A9EFF;
      border-radius: 8px;
      padding: 20px;
      text-align: center;
      margin-bottom: 16px;
    }
    
    .result-label {
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 1px;
      color: #8E8E93;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    
    .result-value {
      font-size: 36px;
      font-weight: 800;
      color: #4A9EFF;
      margin-bottom: 4px;
    }
    
    .result-details { margin-top: 16px; }
    
    .detail-row {
      display: flex;
      justify-content: space-between;
      padding: 6px 0;
      font-size: 12px;
      border-bottom: 1px dashed #E5E5EA;
    }
    
    .detail-row:last-child { border-bottom: none; }
    
    .formula-box {
      background: #F2F2F7;
      border-radius: 6px;
      padding: 12px 16px;
      font-family: 'SF Mono', Monaco, 'Courier New', monospace;
      font-size: 14px;
      color: #1a1a1a;
    }
    
    .nec-box {
      background: #FFF9E6;
      border-left: 4px solid #FFD60A;
      padding: 12px 16px;
      margin-bottom: 16px;
      border-radius: 0 6px 6px 0;
    }
    
    .nec-title {
      font-size: 11px;
      font-weight: 700;
      color: #8E8E93;
      letter-spacing: 1px;
      text-transform: uppercase;
      margin-bottom: 4px;
    }
    
    .nec-reference {
      font-size: 14px;
      font-weight: 600;
      color: #1a1a1a;
    }
    
    .nec-article {
      font-style: italic;
      color: #636366;
      font-size: 12px;
      margin-top: 4px;
    }
    
    .warnings {
      background: #FFF5F5;
      border: 1px solid #FF453A;
      border-radius: 6px;
      padding: 12px 16px;
      margin-bottom: 16px;
    }
    
    .warnings-title {
      font-size: 11px;
      font-weight: 700;
      color: #FF453A;
      letter-spacing: 1px;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    
    .warning-item {
      font-size: 12px;
      color: #1a1a1a;
      padding: 4px 0;
      padding-left: 16px;
      position: relative;
    }
    
    .warning-item:before {
      content: "•";
      color: #FF453A;
      position: absolute;
      left: 4px;
    }
    
    .disclaimer {
      background: #FFF9E6;
      border: 1px solid #FFD60A;
      border-radius: 6px;
      padding: 12px 16px;
      margin-top: 24px;
      font-size: 11px;
      color: #636366;
      line-height: 1.6;
    }
    
    .disclaimer-title {
      font-weight: 700;
      color: #1a1a1a;
      margin-bottom: 4px;
    }
    
    .footer {
      margin-top: 30px;
      padding-top: 16px;
      border-top: 1px solid #E5E5EA;
      text-align: center;
      font-size: 10px;
      color: #8E8E93;
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">ILLWIRED</div>
    <div class="app-name">Conduit & Wire Pro</div>
    <div class="report-type">Calculation Report</div>
  </div>
  
  <div class="content">
    <div class="calc-title">${data.calculatorTitle}</div>
    <div class="date-line">Generated on ${date} at ${time}</div>
    
    <div class="section">
      <div class="section-title">INPUT PARAMETERS</div>
      <table class="inputs-table">${inputsRows}</table>
    </div>
    
    <div class="section">
      <div class="section-title">CALCULATED RESULT</div>
      <div class="result-box">
        <div class="result-label">${data.result.label}</div>
        <div class="result-value">${data.result.value}</div>
      </div>
    </div>
    
    ${formulaHTML}
    
    <div class="nec-box">
      <div class="nec-title">NEC Reference</div>
      <div class="nec-reference">${data.necReference}</div>
      <div class="nec-article">Article ${data.necArticle}</div>
    </div>
    
    ${warningsHTML}
    
    <div class="disclaimer">
      <div class="disclaimer-title">⚠️ FOR REFERENCE ONLY</div>
      This calculation provides reference values based on NEC 2023 formulas. Always verify with a licensed electrician and your local Authority Having Jurisdiction (AHJ). Local codes may have amendments.
    </div>
  </div>
  
  <div class="footer">
    Generated by Conduit & Wire Pro<br>
    NEC 2023 Compliant • illwired.com
  </div>
</body>
</html>`;
}

// Helper functions
function formatLabel(key: string): string {
  return key
    .replace(/([A-Z])/g, ' \$1')
    .replace(/^./, str => str.toUpperCase())
    .replace(/_/g, ' ');
}

function formatValue(value: string | number | boolean | undefined): string {
  if (value === undefined) return '';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  return String(value);
}

function formatDate(date: Date): string {
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function formatDateShort(date: Date): string {
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  });
}

function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
  });
}
